
services:
  backend:
    build:
      context: .            # th∆∞ m·ª•c hi·ªán t·∫°i: final_nodejs
      dockerfile: Dockerfile
    container_name: final_node_backend
    ports:
      - "8080:8080"         # host:container
    env_file:
      - .env                # d√πng c√°c bi·∫øn trong file .env
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200   # üëà CH·ªà ƒê·ªäNH URL ES CHO BACKEND
    depends_on:
      - db
      - elasticsearch       # üëà ƒë·∫£m b·∫£o ES ch·∫°y tr∆∞·ªõc backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: final_node_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # tr√πng v·ªõi DB_PASSWORD ·ªü .env n·∫øu d√πng root
      MYSQL_DATABASE: estorepc
    ports:
      - "3307:3306"         # ƒë·ªÉ connect t·ª´ m√°y host
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: final_node_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"                 # host:container
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  db_data:
  es_data:
